### PR TITLE
Update to chromedriver version 2.23

### PR DESCRIPTION
**Pull request by FlorianDecker**

### CODE REVIEW

**Comment by wilhen01** [comment]
Was just about to do this myself! :+1: please merge @SeriousM!

**Comment by s-kavanagh** [comment]
+ 1 for merging this

**Comment by SeriousM** [comment]
Done! Thank you for contribution!

**Comment by wilhen01** [comment]
Awesome, thanks!

**Comment by s-kavanagh** [comment]
thanks!

**Comment by FlorianDecker** [comment]
Thanks for updating :)

**Pull request merged**
